Changed the style of writing

diff --git a/first_lab/vi b/first_lab/vi
--- a/first_lab/vi
+++ b/first_lab/vi
@@ -1,17 +1,10 @@
 #!/bin/bash
 
 if [[ "$HOME" = "$PWD" ]] 
-
 then
-
-echo "$HOME"
-
-exit 0
-
+	echo "$HOME"
+	exit 0
 else 
-
-echo "ERROR"
-
-exit 1
-
+	echo "ERROR"
+	exit 1
 fi
